### ISSUE TITLE
Fields not declared Optional in ChannelFunction

### ISSUE THREAD

**Issue by michaelhugi** [mvrdevelopment/spec#87]
The following fields are not declared Optional in ChannelFunction
- ModeMaster
- ModeFrom
- ModeTo

**Comment by petrvanekrobe** [comment]
Let me add the previously reported `ModeMaster not defined as optional` here.

**Comment by Firionus** [comment]
Hey Michael, 
great to see you engaged in some work around GDTF :+1: 

Two points from my side:

1. `ModeFrom` and `ModeTo` have a default value of `0/1` so they are already implicitly optional. (See DIN SPEC 15800:2020-07, page 35)

2. Indeed, `ModeMaster` being optional is not in the DIN. But it is relatively clear from the semantics that it is optional, so I would rate this as a clarification of the standard, not as a real change to the format.

**Comment by Firionus** [comment]
It's great to see this closed. 
But how and where did you fix it?

**Comment by fbeasse** [comment]
The fixes are in the aforementioned pull request. For this particular issue: no changes to ModeFrom and ModeTo since, as you indicated, they are already implicitly optional. ModeMaster is now explicitly stated as optional in the description

**Comment by moritzstaffel** [comment]
@Firionus We are currently working on the new GDTF spec. As this is an easy fixed, we just fixed it in the spec text.
The spec text itself is development in another private repo.

**Comment by Firionus** [comment]
> The spec text itself is development in another private repo.

Now I know that developing things in the open isn't always easy, just look at the luca app, and whatever I'm working on also is still in a private repo, so call me a hypocrite, but let me cite your own README:

> The file format is developed using open source formats

For me, this means being able to track these sorts of changes. A public issue tracker is great - I much prefer it over having to talk to support for proprietary software. 
But the way I see it going right now is that a select group of people works through the issue tracker and fixes things. Then, at some point there will be a new proposed spec and I'll have to review lots of changes all at once in a small RFC period. Hence, I'll miss lots of problems which will then create more issues in the long run. And since I can't propose changes in a PR, there'll be even more issues asking you to change stuff, meaning even more work for you. 

What I'm saying is, please consider opening up the spec development in a public repo. It'll make it much easier for independent hobbyists like me to track your development and provide feedback when something is unclear for outsiders. And since changes are split into small commits or PRs, it is much easier to check that each change makes sense. And PRs will enable you to just merge changes that are a no-brainer, instead of writing them yourself. And most importantly, you'd actually do what you set out to do: Develop an *open source* standard. 

I know you'll have to run this by other people in your organizations. And just to give you another argument for them: Me and Michael are already two people working on GDTF from the outside. We may not create the next grandMA, but we want to help make the standard clearer and easier for people to implement. Since you got involved with an open standard, I'm pretty sure this is well aligned with the goals of your companies.

**Comment by moritzstaffel** [comment]
Hi @Firionus 

attached you find the changes that we are making on the spec.

<img width="1448" alt="Bildschirmfoto 2021-08-25 um 14 44 56" src="https://user-images.githubusercontent.com/13522639/130792816-bf728e95-f3e0-450a-bee9-3f8d5f69ab72.png">
<img width="1428" alt="Bildschirmfoto 2021-08-25 um 14 45 10" src="https://user-images.githubusercontent.com/13522639/130792820-1361ea18-cf66-4cdd-b1cc-60f50b1e7354.png">

**Comment by moritzstaffel** [comment]
And yes for sure we want your feedback. That is why we have the proposal repo and share information on what we plan to change on the spec in the monthly meetings.

For the "small" changes, we will have one combined proposal in the end.
Till have are created this, I just the diff that we are currently working on.

**Comment by petrvanekrobe** [comment]
Hi @Firionus ,

just to make sure you are aware - we have made the `work in progress` repo public at the end of last week, so the PRs and merges can be publicly visible. Once all is merged in, we will need to hide it again, as we must not publish the draft verbatim, due to the given legislation.

Hope this helps,
cheers
Petr

**Comment by Firionus** [comment]
Wow, thanks so much guys! Clearing the legal requirements and pushing for more openness - that truly is going a step beyond 🤩

I'm looking forward to reading through your progress when I find the time.
